services:
  algorithm:
    build: .
    volumes:
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
    environment:
      DIDS: '["eb60f87363a36a5ae5cb8373524a8fd976b0cc5f8c40a706c615b857ae0e2974"]'
    #entrypoint: [ "pytest" ]
