services:
  algorithm:
    build: .
    volumes:
      - ./_data/inputs:/data/inputs:ro
      - ./_data/ddos:/data/ddos:ro
      - ./_data/outputs:/data/outputs:rw
      - ./_data/logs:/data/logs:rw
      - ./algorithm/src:/algorithm/src/
      - ./algorithm/tests:/algorithm/tests/
    environment:
      - DID=["ACce67694eD2848dd683c651Dab7Af823b7dd123"]